name: Build Package
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
        with:
          bun-version: latest

      - name: 构建plugin
        run: |
          bun install
          bun run build
          mkdir -p ${{ runner.temp }}/temp/plugin
          cp -r package.json CHANGELOG.md README.md LICENSE config lib ${{ runner.temp }}/temp/plugin

      - name: 上传plugin构建产物
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: plugin
          path: ${{ runner.temp }}/temp/plugin
