name: Build Package
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest

      - name: 构建plugin
        run: |
          bun install
          bun run build
          mkdir -p ${{ runner.temp }}/temp/plugin
          cp -r package.json CHANGELOG.md README.md LICENSE config lib ${{ runner.temp }}/temp/plugin

      - name: 上传plugin构建产物
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: plugin
          path: ${{ runner.temp }}/temp/plugin
